Ext.define('PENKNIFE.view.auth.CountriesStore', {
    extend: 'Ext.data.ArrayStore',

    alias: 'view.auth.CountriesStore',
    fields: [
        {name: 'codice'},
        {name: 'valore'}
    ],

    data: [
        [null, `Choose..`],
        [`AL`, `Albania`],
        [`AS`, `American Samoa`],
        [`AD`, `Andorra`],
        [`AG`, `Antigua & Barbuda`],
        [`AR`, `Argentina`],
        [`AM`, `Armenia`],
        [`AW`, `Aruba`],
        [`AU`, `Australia`],
        [`AT`, `Austria`],
        [`AO`, `Angola`],
        [`AZ`, `Azerbaijan`],
        [`BS`, `Bahamas`],
        [`BH`, `Bahrain`],
        [`BD`, `Bangladesh`],
        [`BB`, `Barbados`],
        [`BY`, `Belarus`],
        [`BE`, `Belgium`],
        [`BZ`, `Belize`],
        [`BJ`, `Benin`],
        [`BM`, `Bermuda`],
        [`BT`, `Bhutan`],
        [`BA`, `Bosnia`],
        [`BW`, `Botswana`],
        [`BR`, `Brazil`],
        [`VG`, `British Virgin Islan`],
        [`BN`, `Brunei`],
        [`BG`, `Bulgaria`],
        [`BF`, `Burkina Faso`],
        [`BI`, `Burundi`],
        [`KH`, `Cambodia`],
        [`CM`, `Cameroon`],
        [`CA`, `Canada`],
        [`CF`, `Central African`],
        [`CV`, `Cape Verde`],
        [`KY`, `Cayman Islands`],
        [`CT`, `Central African Rep`],
        [`TD`, `Chad`],
        [`CL`, `Chile`],
        [`CO`, `Colombia`],
        [`CK`, `Cook Islands`],
        [`CR`, `Costa Rica`],
        [`CI`, `Cote d'Ivoire`],
        [`HR`, `Croatia`],
        [`CY`, `Cyprus`],
        [`CZ`, `Czech Republic`],
        [`DK`, `Denmark`],
        [`DJ`, `Djibouti`],
        [`DM`, `Dominica`],
        [`DO`, `Dominican Republic`],
        [`EC`, `Ecuador`],
        [`GQ`, `Eqiatorial Guinea`],
        [`EG`, `Egypt`],
        [`SV`, `El Salvador`],
        [`ER`, `Eritrea`],
        [`EE`, `Estonia`],
        [`ET`, `Ethiopia`],
        [`FO`, `Faeroe Islands`],
        [`FM`, `Fed St of Micronesia`],
        [`FJ`, `Fiji`],
        [`FI`, `Finland`],
        [`FR`, `France`],
        [`GF`, `French Guiana`],
        [`PF`, `French Polynesia`],
        [`GA`, `Gabon`],
        [`GM`, `Gambia`],
        [`GE`, `Georgia`],
        [`DE`, `Germany`],
        [`GI`, `Gibraltar`],
        [`GL`, `Greenland`],
        [`GD`, `Grenada`],
        [`GP`, `Guadeloupe`],
        [`GU`, `Guam`],
        [`GT`, `Guatemala`],
        [`GN`, `Guinea`],
        [`GW`, `Guinea-Bissau`],
        [`GY`, `Guyana`],
        [`HT`, `Haiti`],
        [`HN`, `Honduras`],
        [`HK`, `Hong Kong`],
        [`HU`, `Hungary`],
        [`IS`, `Iceland`],
        [`IN`, `India`],
        [`IE`, `Ireland`],
        [`IQ`, `Iraq`],
        [`IL`, `Israel`],
        [`IT`, `Italy`],
        [`JM`, `Jamaica`],
        [`JP`, `Japan`],
        [`JO`, `Jordan`],
        [`KZ`, `Kazakhstan`],
        [`KI`, `Kiribati`],
        [`KW`, `Kuwait`],
        [`KG`, `Kyrgyzstan`],
        [`LA`, `Laos`],
        [`LV`, `Latvia`],
        [`LB`, `Lebanon`],
        [`LS`, `Lesotho`],
        [`LR`, `Liberia`],
        [`LY`, `Libya`],
        [`LI`, `Lichtenstein`],
        [`LT`, `Lithuania`],
        [`LU`, `Luxembourg`],
        [`MO`, `Macau`],
        [`MK`, `Macedonia`],
        [`MG`, `Madagascar`],
        [`MW`, `Malawi`],
        [`MV`, `Maldives`],
        [`ML`, `Mali`],
        [`MT`, `Malta`],
        [`MH`, `Marshall Islands`],
        [`MQ`, `Martinique`],
        [`MU`, `Mauritius`],
        [`MR`, `Mauuritania`],
        [`MX`, `Mexico`],
        [`MD`, `Moldava`],
        [`MC`, `Monaco`],
        [`MN`, `Mongolia`],
        [`ME`, `Montenegro`],
        [`MS`, `Monteserrat`],
        [`MA`, `Morocco`],
        [`MZ`, `Mozambique`],
        [`NA`, `Namibia`],
        [`NR`, `Nauru`],
        [`NP`, `Nepal`],
        [`NL`, `Netherlands`],
        [`AN`, `Netherlands Antilles`],
        [`NC`, `New Caledonia`],
        [`NZ`, `New Zealand`],
        [`NI`, `Nicaragua`],
        [`NE`, `Niger`],
        [`NF`, `Norfolk Island`],
        [`NO`, `Norway`],
        [`OM`, `Oman`],
        [`PK`, `Pakistan`],
        [`PW`, `Palau`],
        [`PA`, `Panama`],
        [`PG`, `Papua New Guinea`],
        [`PY`, `Paraguay`],
        [`CN`, `Peoples Rep of China`],
        [`PE`, `Peru`],
        [`PH`, `Phillipines`],
        [`PL`, `Poland`],
        [`PT`, `Portugal`],
        [`PR`, `Puerto Rico`],
        [`QA`, `Qatar`],
        [`RW`, `Rawanda`],
        [`CG`, `Republic of Congo`],
        [`YE`, `Republic of Yemen`],
        [`RE`, `Reunion`],
        [`RO`, `Romania`],
        [`SM`, `San Marino`],
        [`SA`, `Saudi Arabia`],
        [`SN`, `Senegal`],
        [`RS`, `Serbia`],
        [`SC`, `Seychelles`],
        [`SL`, `Sierra Leone`],
        [`SG`, `Singapore`],
        [`SK`, `Slovakia`],
        [`SI`, `Slovenia`],
        [`SB`, `Solomon Islands`],
        [`ZA`, `South Africa`],
        [`KR`, `South Korea`],
        [`ES`, `Spain`],
        [`LK`, `Sri Lanka`],
        [`NT`, `St.Barthelemy`],
        [`KN`, `St.Kitts & Nevis`],
        [`SH`, `St Helena`],
        [`LC`, `St.Lucia`],
        [`VC`, `St.Vincent&Grenadine`],
        [`SD`, `Sudan`],
        [`SR`, `Suriname`],
        [`SZ`, `Swaziland`],
        [`SE`, `Sweeden`],
        [`CH`, `Switzerland`],
        [`TW`, `Taiwan`],
        [`TJ`, `Tajikistan`],
        [`TZ`, `Tanzania`],
        [`TH`, `Thailand`],
        [`TG`, `Togo`],
        [`TO`, `Tonga`],
        [`TT`, `Trinidad & Tobago`],
        [`TN`, `Tunisia`],
        [`TR`, `Turkey`],
        [`TC`, `Turks & Caicos Isles`],
        [`TM`, `Turkmenistam`],
        [`TV`, `Tuvalu`],
        [`UA`, `Ukraine`],
        [`AE`, `United Arab Emirates`],
        [`GB`, `United Kingdom`],
        [`US`, `United States`],
        [`UY`, `Uruguay`],
        [`VI`, `US Virgin Islands`],
        [`UZ`, `Uzbekistan`],
        [`VU`, `Vanuatu`],
        [`VA`, `Vatican City`],
        [`VE`, `Venezuela`],
        [`WF`, `Wallis & Futuna Is`],
        [`WS`, `Western Samoa`],
        [`ZM`, `Zambia`]
    ]
});
